package org.fkjava.j1303.ec.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fkjava.j1303.ec.entity.model.ArticleType;
import org.fkjava.j1303.ec.entity.model.ArticleTypeExample;

public interface ArticleTypeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int countByExample(ArticleTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByExample(ArticleTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insert(ArticleType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insertSelective(ArticleType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	List<ArticleType> selectByExample(ArticleTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	ArticleType selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExampleSelective(@Param("record") ArticleType record,
			@Param("example") ArticleTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExample(@Param("record") ArticleType record,
			@Param("example") ArticleTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKeySelective(ArticleType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_article_type
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKey(ArticleType record);

	/**
	 * 获取表中CODE的最大值。如果parentCode不为空，只查询parentCode对应的子类型的最大CODE
	 * 
	 * @param parentCode
	 *            上级类型的CODE，如果该参数不为空，表示查询下级的最大CODE；否则是一级类型的最大CODE
	 * @param codeLength
	 *            如果parentCode为空,该参数生效.用于获取一级类型的CODE时使用
	 * @return
	 */
	String getMaxCode(@Param("parentCode") String parentCode,
			@Param("codeLength") int codeLength);
}