package org.fkjava.j1303.ec.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fkjava.j1303.ec.entity.model.Article;
import org.fkjava.j1303.ec.entity.model.ArticleExample;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_article
     *
     * @mbggenerated Fri Jun 28 16:17:06 CST 2013
     */
    int updateByPrimaryKey(Article record);
}