package org.fkjava.j1303.ec.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fkjava.j1303.ec.entity.model.OrderItem;
import org.fkjava.j1303.ec.entity.model.OrderItemExample;
import org.fkjava.j1303.ec.entity.model.OrderItemKey;

public interface OrderItemMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int countByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByPrimaryKey(OrderItemKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insert(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insertSelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	List<OrderItem> selectByExample(OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	OrderItem selectByPrimaryKey(OrderItemKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExampleSelective(@Param("record") OrderItem record,
			@Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExample(@Param("record") OrderItem record,
			@Param("example") OrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKeySelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order_item
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKey(OrderItem record);
}