package org.fkjava.j1303.ec.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fkjava.j1303.ec.entity.model.Order;
import org.fkjava.j1303.ec.entity.model.OrderExample;

public interface OrderMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	Order selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Order record,
			@Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByExample(@Param("record") Order record,
			@Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ec_order
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	int updateByPrimaryKey(Order record);

}