package org.fkjava.j1303.ec.entity.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fkjava.j1303.ec.entity.model.User;
import org.fkjava.j1303.ec.entity.model.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ec_user
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    int updateByPrimaryKey(User record);
}