package org.fkjava.j1303.ec.entity.model;

import java.util.Date;

public class Article {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.ID
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.TITLE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.SUPPLIER
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String supplier;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.PRICE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private Double price;
	private Double discount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.LOCALITY
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String locality;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.PUTAWAY_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private Date putawayDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.STORAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private Integer storage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.IMAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String image;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.DESCRIPTION
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.TYPE_CODE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private String typeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.CREATE_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_article.DISABLED
	 * 
	 * @mbggenerated Fri Jun 28 16:25:06 CST 2013
	 */
	private Boolean disabled = Boolean.FALSE;

	private ArticleType articleType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.ID
	 * 
	 * @return the value of ec_article.ID
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.ID
	 * 
	 * @param id
	 *            the value for ec_article.ID
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.TITLE
	 * 
	 * @return the value of ec_article.TITLE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.TITLE
	 * 
	 * @param title
	 *            the value for ec_article.TITLE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.SUPPLIER
	 * 
	 * @return the value of ec_article.SUPPLIER
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.SUPPLIER
	 * 
	 * @param supplier
	 *            the value for ec_article.SUPPLIER
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier == null ? null : supplier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.PRICE
	 * 
	 * @return the value of ec_article.PRICE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.PRICE
	 * 
	 * @param price
	 *            the value for ec_article.PRICE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.LOCALITY
	 * 
	 * @return the value of ec_article.LOCALITY
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getLocality() {
		return locality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.LOCALITY
	 * 
	 * @param locality
	 *            the value for ec_article.LOCALITY
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setLocality(String locality) {
		this.locality = locality == null ? null : locality.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.PUTAWAY_DATE
	 * 
	 * @return the value of ec_article.PUTAWAY_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public Date getPutawayDate() {
		return putawayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.PUTAWAY_DATE
	 * 
	 * @param putawayDate
	 *            the value for ec_article.PUTAWAY_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setPutawayDate(Date putawayDate) {
		this.putawayDate = putawayDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.STORAGE
	 * 
	 * @return the value of ec_article.STORAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public Integer getStorage() {
		return storage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.STORAGE
	 * 
	 * @param storage
	 *            the value for ec_article.STORAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setStorage(Integer storage) {
		this.storage = storage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.IMAGE
	 * 
	 * @return the value of ec_article.IMAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.IMAGE
	 * 
	 * @param image
	 *            the value for ec_article.IMAGE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.DESCRIPTION
	 * 
	 * @return the value of ec_article.DESCRIPTION
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.DESCRIPTION
	 * 
	 * @param description
	 *            the value for ec_article.DESCRIPTION
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.TYPE_CODE
	 * 
	 * @return the value of ec_article.TYPE_CODE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.TYPE_CODE
	 * 
	 * @param typeCode
	 *            the value for ec_article.TYPE_CODE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode == null ? null : typeCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.CREATE_DATE
	 * 
	 * @return the value of ec_article.CREATE_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for ec_article.CREATE_DATE
	 * 
	 * @mbggenerated Fri Jun 28 16:17:06 CST 2013
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_article.DISABLED
	 * 
	 * @return the value of ec_article.DISABLED
	 * 
	 * @mbggenerated Fri Jun 28 16:25:06 CST 2013
	 */
	public Boolean getDisabled() {
		return disabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_article.DISABLED
	 * 
	 * @param disabled
	 *            the value for ec_article.DISABLED
	 * 
	 * @mbggenerated Fri Jun 28 16:25:06 CST 2013
	 */
	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

	/**
	 * @return the articleType
	 */
	public ArticleType getArticleType() {
		return articleType;
	}

	/**
	 * @param articleType
	 *            the articleType to set
	 */
	public void setArticleType(ArticleType articleType) {
		this.articleType = articleType;
	}

	/**
	 * @return the discount
	 */
	public Double getDiscount() {
		if (discount == null || discount <= 0.0) {
			discount = 10.0;
		}
		return discount;
	}

	/**
	 * 计算折扣价
	 * 
	 * @return
	 */
	public Double getDiscountPrice() {
		return this.getPrice() * (this.getDiscount() / 10);
	}

	/**
	 * @param discount
	 *            the discount to set
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}
}