package org.fkjava.j1303.ec.entity.model;

public class ArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_article_type.CODE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_article_type.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_article_type.REMARK
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_article_type.CODE
     *
     * @return the value of ec_article_type.CODE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_article_type.CODE
     *
     * @param code the value for ec_article_type.CODE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_article_type.NAME
     *
     * @return the value of ec_article_type.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_article_type.NAME
     *
     * @param name the value for ec_article_type.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_article_type.REMARK
     *
     * @return the value of ec_article_type.REMARK
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_article_type.REMARK
     *
     * @param remark the value for ec_article_type.REMARK
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}