package org.fkjava.j1303.ec.entity.model;

public class OrderItemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_order_item.ORDER_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_order_item.ARTICLE_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Integer articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_order_item.ORDER_ID
     *
     * @return the value of ec_order_item.ORDER_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_order_item.ORDER_ID
     *
     * @param orderId the value for ec_order_item.ORDER_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_order_item.ARTICLE_ID
     *
     * @return the value of ec_order_item.ARTICLE_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_order_item.ARTICLE_ID
     *
     * @param articleId the value for ec_order_item.ARTICLE_ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
}