package org.fkjava.j1303.ec.entity.model;

public class OrderItem extends OrderItemKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order_item.ORDER_NUM
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Integer orderNum;
	private Article article;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order_item.ORDER_NUM
	 * 
	 * @return the value of ec_order_item.ORDER_NUM
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order_item.ORDER_NUM
	 * 
	 * @param orderNum
	 *            the value for ec_order_item.ORDER_NUM
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * 获取该订单条目的小计价格，以优惠有的价格计算。
	 * 
	 * @return
	 */
	public Double getAmount() {
		return (this.getArticle().getDiscountPrice().doubleValue())
				* (this.getOrderNum().doubleValue());
	}

	/**
	 * @return the article
	 */
	public Article getArticle() {
		return article;
	}

	/**
	 * @param article
	 *            the article to set
	 */
	public void setArticle(Article article) {
		this.article = article;
	}
}