package org.fkjava.j1303.ec.entity.model;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

public class Order {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.ORDER_CODE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private String orderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.CREATE_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.SEND_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Date sendDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.STATUS
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.AMOUNT
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Double amount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ec_order.USER_ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	private Integer userId;

	private List<OrderItem> orderItemList = new LinkedList<>();
	private User user;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.ID
	 * 
	 * @return the value of ec_order.ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.ID
	 * 
	 * @param id
	 *            the value for ec_order.ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.ORDER_CODE
	 * 
	 * @return the value of ec_order.ORDER_CODE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.ORDER_CODE
	 * 
	 * @param orderCode
	 *            the value for ec_order.ORDER_CODE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode == null ? null : orderCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.CREATE_DATE
	 * 
	 * @return the value of ec_order.CREATE_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for ec_order.CREATE_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.SEND_DATE
	 * 
	 * @return the value of ec_order.SEND_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Date getSendDate() {
		return sendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.SEND_DATE
	 * 
	 * @param sendDate
	 *            the value for ec_order.SEND_DATE
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.STATUS
	 * 
	 * @return the value of ec_order.STATUS
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.STATUS
	 * 
	 * @param status
	 *            the value for ec_order.STATUS
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.AMOUNT
	 * 
	 * @return the value of ec_order.AMOUNT
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.AMOUNT
	 * 
	 * @param amount
	 *            the value for ec_order.AMOUNT
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ec_order.USER_ID
	 * 
	 * @return the value of ec_order.USER_ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ec_order.USER_ID
	 * 
	 * @param userId
	 *            the value for ec_order.USER_ID
	 * 
	 * @mbggenerated Mon Jun 24 16:59:23 CST 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * @return the orerItemList
	 */
	public List<OrderItem> getOrderItemList() {
		return orderItemList;
	}

	/**
	 * @param orerItemList
	 *            the orerItemList to set
	 */
	public void setOrderItemList(List<OrderItem> orderItemList) {
		this.orderItemList = orderItemList;
	}

	/**
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * @param user
	 *            the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}
}