package org.fkjava.j1303.ec.entity.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.LOGIN_NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.PASS_WORD
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.SEX
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.EMAIL
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.PHONE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.ADDRESS
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.ROLE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.CREATE_DATE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.ACTIVE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ec_user.DISABLED
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    private Boolean disabled = Boolean.FALSE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.ID
     *
     * @return the value of ec_user.ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.ID
     *
     * @param id the value for ec_user.ID
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.LOGIN_NAME
     *
     * @return the value of ec_user.LOGIN_NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.LOGIN_NAME
     *
     * @param loginName the value for ec_user.LOGIN_NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.PASS_WORD
     *
     * @return the value of ec_user.PASS_WORD
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.PASS_WORD
     *
     * @param passWord the value for ec_user.PASS_WORD
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.NAME
     *
     * @return the value of ec_user.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.NAME
     *
     * @param name the value for ec_user.NAME
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.SEX
     *
     * @return the value of ec_user.SEX
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.SEX
     *
     * @param sex the value for ec_user.SEX
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.EMAIL
     *
     * @return the value of ec_user.EMAIL
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.EMAIL
     *
     * @param email the value for ec_user.EMAIL
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.PHONE
     *
     * @return the value of ec_user.PHONE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.PHONE
     *
     * @param phone the value for ec_user.PHONE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.ADDRESS
     *
     * @return the value of ec_user.ADDRESS
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.ADDRESS
     *
     * @param address the value for ec_user.ADDRESS
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.ROLE
     *
     * @return the value of ec_user.ROLE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.ROLE
     *
     * @param role the value for ec_user.ROLE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.CREATE_DATE
     *
     * @return the value of ec_user.CREATE_DATE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.CREATE_DATE
     *
     * @param createDate the value for ec_user.CREATE_DATE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.ACTIVE
     *
     * @return the value of ec_user.ACTIVE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.ACTIVE
     *
     * @param active the value for ec_user.ACTIVE
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ec_user.DISABLED
     *
     * @return the value of ec_user.DISABLED
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ec_user.DISABLED
     *
     * @param disabled the value for ec_user.DISABLED
     *
     * @mbggenerated Mon Jun 24 16:59:23 CST 2013
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
}